Rails.application.routes.draw do
  # Existing authentication routes (generated by rails generate authentication)
  resource :session
  
  # Add these lines for user registration:
  resources :users, only: [:new, :create]
  
  # Your other routes
  resources :ingredients
  
  root "ingredients#index"
end